### ISSUE TITLE
Documenter.jl eats the inline math markup

### ISSUE THREAD

**Issue by mitya57** [JuliaDocs/Documenter.jl#377] opened 2016-12-15 20:26 UTC
One more issue that is more severe than the previous one: it looks like it is impossible to use the inline LaTeX markup `\(...\)` in the documents at all.

If I have a formula `\( foo \)` in my `src/index.md`, it turns into `( foo )` in the generated `build/index.md`. A workaround is to use the double escaping (`\\(...\\)`), but this is wrong.

**Comment by MichaelHatherly** [comment] 2016-12-15 21:32
The markdown parser is [defined](https://github.com/JuliaLang/julia/tree/master/base/markdown) upstream from Documenter itself. Regarding the actual behaviour seen here, as far as I recall [that escaping](https://github.com/JuliaLang/julia/blob/38ff38c3328858df042b7e0fcb72385d7f4c4a7a/base/markdown/Common/inline.jl#L129-L138) is based on what [pandoc does](http://pandoc.org/try/?text=%5C(+foo+%5C)%0A%0A%5C%5C(+foo+%5C%5C)&from=markdown&to=html). Whether it's the right thing to do is debatable, but changing it would probably break someones docs. Julia's own flavour of markdown supports `$` and ``` `` ``` pairs for inline maths, so I'm not sure whether we need to support an additional one as well.

**Comment by juliohm** [comment] 2016-12-16 09:46
@MichaelHatherly the $ symbol does not work, I tried `` and it does not work either. Where is this documented in `Documenter.jl`?

**Comment by MichaelHatherly** [comment] 2016-12-16 10:06
> Where is this documented

In [the manual](http://docs.julialang.org/en/stable/manual/documentation/#id1), double backticks are the preferred method over `$` since it doesn't conflict with interpolation, but we'll be keeping `$` around for the time being at least.

Also, Documenter has a [page](https://juliadocs.github.io/Documenter.jl/stable/man/latex.html) that provides some additional help.

> the $ symbol does not work, I tried `` and it does not work either.

Which version of Julia, and packages are you using?

**Comment by juliohm** [comment] 2016-12-16 10:16
>Julia Version 0.5.1-pre+31
Commit 6a1e339* (2016-11-17 17:50 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

> - Documenter                    0.8.4

**Comment by MichaelHatherly** [comment] 2016-12-16 10:20
Thanks. If the docs you are trying to build available on GitHub somewhere then I can take a look a little later today to see why that syntax isn't working.

**Comment by juliohm** [comment] 2016-12-16 10:22
Thank you @MichaelHatherly , the docs are for the `ImageQuilting.jl` package: https://github.com/juliohm/ImageQuilting.jl

I am trying to use LaTeX notation for the interval [0,1] at the bottom of the `index.md` file.

**Comment by MichaelHatherly** [comment] 2016-12-16 10:33
The following diff appears to work for me:

```diff
diff --git a/docs/mkdocs.yml b/docs/mkdocs.yml
index a3ca4b1..f474254 100644
--- a/docs/mkdocs.yml
+++ b/docs/mkdocs.yml
@@ -9,7 +9,7 @@ extra_css:
   - assets/Documenter.css
 
 extra_javascript:
-  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTMLorMML
+  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
   - assets/mathjaxhelper.js
 
 markdown_extensions:
diff --git a/docs/src/index.md b/docs/src/index.md
index 4693608..af4ed2f 100644
--- a/docs/src/index.md
+++ b/docs/src/index.md
@@ -79,5 +79,5 @@ mean, dev = voxelreuse(training_image::AbstractArray,
                        threads=CPU_PHYSICAL_CORES, gpu=false)
 
-with `mean` in the interval [0,1] and `dev` the standard deviation. The approximation
+with `mean` in the interval ``[0,1]`` and `dev` the standard deviation. The approximation
 gets better as `nreal` is made larger.
```

**Comment by mitya57** [comment] 2016-12-16 10:53
> ```diff
> -  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTMLorMML
> +  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
> ```

It is strange that this is needed. First of all, the output types are overridden in [`mathjaxhelper.js`](https://github.com/JuliaDocs/Documenter.jl/blob/master/assets/mkdocs/mathjaxhelper.js), so this should have no effect. Then, there is nothing wrong in `HTMLorMML`: MathJax will not try to output MathML unless it is supported by the browser engine.

> the $ symbol does not work

For the single-dollar delimiters, try changing in your `mkdocs.yml`:
```yaml
markdown_extensions:
  ...
  - mdx_math
```

to
```yaml
markdown_extensions:
  ...
  - mdx_math:
      enable_dollar_delimiter: True
```

These delimiters are disabled by default because the dollar signs can frequently occur in non-mathematical texts.

**Comment by juliohm** [comment] 2016-12-16 11:06
@MichaelHatherly, the trick of removing the `MML` suffix from that URL worked. I don't have much background in Javascript nor web programming, so this is quite mysterious.

@mitya57, I think the dollar sign is avoided in Julia documentation because the symbol is used for interpolation in strings:
```julia
year = 2017
println("Happy $year !")
```
>Happy 2017 !

I believe we should document this issue better of fix it somehow.

**Comment by MichaelHatherly** [comment] 2016-12-16 12:46
> I believe we should document this issue better of fix it somehow.

Yes, if there's anything in particular that's not clear enough then I'd definitely welcome PRs to clarify things. Note that both URLs provided in Documenter's docs do work correctly:

- https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
- https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

so I'm not sure how that should be clarified better. Perhaps just remove the second one to avoid confusion.

**Comment by juliohm** [comment] 2016-12-17 14:48
I see, what should we do? Close the issue and be aware of this URL detail?

**Comment by MichaelHatherly** [comment] 2016-12-18 09:51
> I see, what should we do? Close the issue and be aware of this URL detail?

That, or updating the docs to make it more clear is fine too if you've some clearer wording that would help others not get tripped up by this.

**Comment by sbromberger** [comment] 2017-06-02 16:26
Hi all,

I'm wondering whether this is the cause/related to https://github.com/JuliaGraphs/LightGraphs.jl/issues/639 - I've just added the 
```
markdown_extensions:
  ...
  - mdx_math:
      enable_dollar_delimiter: True
```
to my .yml but reading further I'm not sure whether this is wise. Advice please?

**Comment by odow** [comment] 2023-11-01 21:51
Closing because this seems resolved. With
````
`[ ]`: interval [0,1] and

``` ``[ ]`` ```: interval ``[0,1]`` and

`$[ ]`: interval $[0,1]$ and

`\\[ [ ] \\]`: interval \\[[0,1]\\] and

`\[ [ ] \]`: interval \[[0,1]\] and

`\( [ ] \)`: interval \([0,1]\) and

`\\( [ ] \\)`: interval \\([0,1]\\) and
````

I get

![image](https://github.com/JuliaDocs/Documenter.jl/assets/8177701/770dccaa-3068-4272-9e48-d1fc74e3fd79)

So ``` ``[]`` ``` and `$[]$` work for inline as expected, and `\\[ \\]`` is display.

**Closed by odow** 2023-11-01 21:51 UTC
Labels: Status: Available, Type: Documentation
