### ISSUE TITLE
Citing this library

### ISSUE THREAD

**Issue by vladdez** [JuliaDocs/Documenter.jl#2603] opened 2024-11-08 18:06 UTC
Hello! I would like to cite your library in my paper, but couldn't find any citations here. Ideally would be great if you would have a "Cite his repository" button and doi.

**Comment by goerz** [comment] 2024-11-08 18:18
Duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/2386

**Closed by goerz** 2024-11-08 18:18 UTC

**Comment by vladdez** [comment] 2024-11-08 18:36
Thanks for showing this issue, but I think it still could be done something more.
1) Some journals like JOOS requires citations with doi. So would be great if Documenter will have one.
2) Also would be much helpful (instead of searching in issues) to put citation on a main page: eather in index.md or in Cite this repository like on the screenshot. 
![image](https://github.com/user-attachments/assets/a35029dd-574b-4bf0-a8f3-6c4c8425a0d3)
3) Also I guess more correct title will be "Documenter.jl" instead of just "Documenter".

**Comment by goerz** [comment] 2024-11-08 19:07
> Thanks for showing this issue, but I think it still could be done something more.

That issue is still open

> Some journals like JOOS requires citations with doi

They require a DOI for materials that _have_ a DOI. There are a great many things you could cite that simply don't have a DOI ("personal correspondence").

> put [...] Cite this repository like on the screenshot

Yes, that seems like something that's potentially worthwhile for @mortenpi to set up at some point.

On the other hand, Documenter isn't the kind of package that you should (or at least that I would) cite in a publication. Except under some unusual circumstances, like if you were writing a paper about open source and its documentation systems, i.e., `Documenter` was in some way the subject of your paper. If I was reviewing a paper where the authors started to cite the software stack not directly related to the research, I would flag that as inappropriate.

Not that the creators and maintainers of Documenter don't deserve full credit, but you can do that via the footer in the documentation of your packages.
