### ISSUE TITLE
The prefixes for some methods are too long

### ISSUE THREAD

**Issue by singularitti** [JuliaDocs/Documenter.jl#1064] opened 2019-07-11 04:32 UTC
For example I have a [package](https://github.com/singularitti/NumericalMethodsInQuantumMechanics.jl/tree/develop). I nest a module deeply, so the exported functions in that module will have long prefix specifying the module structure, e.g., in [this page](https://singularitti.github.io/NumericalMethodsInQuantumMechanics.jl/dev/EigenvalueProblems/NumerovMethod/#Numerov's-method-1), `numerov_iter` shows as 
<img width="777" alt="CleanShot 2019-07-11 at 00 30 17@2x" src="https://user-images.githubusercontent.com/25192197/61022291-1aefcb00-a373-11e9-8ffc-cb3277fafde3.png">. Is that the way the prefix supposed to be? Is there a way for not showing `NumericalMethodsInQuantumMechanics`? It is apparent that this function is bonded to this package.

**Comment by mortenpi** [comment] 2019-07-12 06:20
I don't think anything exists to drop the prefix at the moment. In general, I would say that you want the prefix to be there since you want to make it clear what function it is exactly.

But we could consider having an at-meta option that allows you to, say, set the module to which the identifiers should be relative to. I'd be happy to review a PR implementing something like that.

**Comment by odow** [comment] 2023-10-31 23:52
Duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/253

**Closed** 2023-11-01 00:02 UTC
Labels: Type: Enhancement
