### ISSUE TITLE
Citing and DOI

### ISSUE THREAD

**Issue by vladdez** [JuliaDocs/Documenter.jl#2613] opened 2024-12-03 13:04 UTC
I would like to cite your package, but there is no even DOI. Would be great to have DOI at least and "Cite this project" button at best.

**Comment by goerz** [comment] 2024-12-03 13:22
Duplicate of #2386

DOIs are typically only for formally published materials; you do not need a DOI to cite this package, see https://github.com/JuliaDocs/Documenter.jl/issues/2603#issuecomment-2465557853

**Closed by goerz** 2024-12-03 13:22 UTC
