### ISSUE TITLE
feature request: print the filtered rather than unfiltered diff for doctest errors

### ISSUE THREAD

**Issue by dsweber2** [JuliaDocs/Documenter.jl#2225] opened 2023-08-20 19:35 UTC
When trying to debug non-matching doctests where there's a filter active, having the actual strings compared rather than the original output would be useful in debugging.

**Comment by mortenpi** [comment] 2023-08-20 21:26
Duplicate of #2221.

**Closed by mortenpi** 2023-08-20 21:26 UTC
