### ISSUE TITLE
`strict=true` not detecting exported name without a docstring

### ISSUE THREAD

**Issue by jariji** [JuliaDocs/Documenter.jl#2244] opened 2023-09-05 20:46 UTC
This macro is exported but undocumented so I expected `strict=true` to complain.

```jl
julia> using Markdown

julia> md""


help?> md""
  No documentation found.

  Markdown.@md_str is a macro.
```

https://github.com/JuliaLang/julia/issues/51167

**Comment by mortenpi** [comment] 2023-09-05 23:56
This is sort of working as intended -- missidocs only complains about existing _docstrings_ that are not included in the manual, but it does not check that all exports have docstrings. That said, that might be something we could add.. although maybe this kind of a check should live in a separate package, since it's not directly related to the documentation build.

**Comment by odow** [comment] 2023-11-01 02:56
Closing as a duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/1917

**Closed by odow** 2023-11-01 02:56 UTC
Labels: Type: Enhancement, Status: Speculative
