### ISSUE TITLE
Something is going wrong when using mp3 files in the docs

### ISSUE THREAD

**Issue by Datseris** [JuliaDocs/Documenter.jl#1260] opened 2020-03-12 20:31 UTC
I have some documentation in which I need to inline an mp3 file to be played. I do this with an `@raw` block, using 
```
<audio controls>
 <source src="blackbitter.mp3" type="audio/mpeg">
</audio>
```
in my markdown file. The mp3 file and the markdown file are in the same folder.

Building the documentation locally, everything is working fine. But when I push the changes, the online builted and hosted documentation doesn't play the mp3 file, and in fact in general seems to not be able to find it, as if for some reason the file was not copied properly into the build folder.

Full example: 

* mp3 file: https://github.com/JuliaMusic/JuliaMusic_documentation.jl/blob/master/docs/src/blog/blackbitter.mp3
* markdown doc file: https://raw.githubusercontent.com/JuliaMusic/JuliaMusic_documentation.jl/master/docs/src/blog/gaddisms.md
* resulting hosted page (the mp3 player is just above the section I link): https://juliamusic.github.io/JuliaMusic_documentation.jl/latest/blog/gaddisms/#Creating-the-Gaddisms-with-Julia-code-1

**Comment by fredrikekre** [comment] 2020-03-12 20:35
Duplicate of #921

**Closed by fredrikekre** 2020-03-12 20:35 UTC
