### ISSUE TITLE
Documenting a functor

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaDocs/Documenter.jl#1270] opened 2020-03-22 19:02 UTC
Is this something that Documenter cannot handle at this point?
```
┌ Warning: unable to get the binding for '(la::LocAccess)(j::Int64)' in `@docs` block in src\man\functions.md from expression ':((la::LocAccess)(j::Int64))' in module MeshCore
│ ```@docs
│ locations(la::LocAccess{N, T}) where {N, T}
│ (la::LocAccess)(j::Int64)
│ ```
│   exception = `binding` cannot understand expression `la::LocAccess`.
└ @ Documenter.Expanders C:\Users\PKrysl\.julia\packages\Documenter\RrEcY\src\Expanders.jl:285
```
Or, perhaps I'm not doing it right?

**Comment by mileslucas** [comment] 2020-03-23 00:21
This has come up before (empty while I search for related issues) but basically it's a base Julia failure to find these methods consistently, not a Documenter issue, since Documenter uses (looking this up, too) for finding the docstrings.

**Comment by PetrKryslUCSD** [comment] 2020-03-23 00:55
Thanks. I couldn't find anything relevant concerning this failure. Now I at least know when to stop searching.

**Comment by mileslucas** [comment] 2020-03-23 01:00
Although, this issue is not the same issue. You have to use
```julia
LocAccess
```
which _should_ automatically display the type and the functor (see https://juliaastro.github.io/DustExtinction.jl/dev/dust_maps/#DustExtinction.SFD98Map for an example) but I've had problems with the _automatic_ part.

**Comment by mileslucas** [comment] 2020-03-23 01:01
One design pattern I've used to get around the sometimes failure of finding this docstring is to put the functor docs inside the type docs (under something like a `# Usage` header).

**Comment by PetrKryslUCSD** [comment] 2020-03-23 18:23
Thanks for the pointers!

**Comment by mileslucas** [comment] 2020-03-23 20:39
Here’s the original #558

**Comment by mortenpi** [comment] 2020-05-07 10:10
Closing this as duplicate of #558.

**Closed** 2020-05-07 10:11 UTC
Labels: Type: Bug, Type: Upstream
