### ISSUE TITLE
doctest for modules without documentation and for separate functions

### ISSUE THREAD

**Issue by xvries** [JuliaDocs/Documenter.jl#1868] opened 2022-07-07 07:32 UTC
It would be nice to be able to run `doctest()` on:

1. A module without a `*/docs/src/` directory. Right now it throws an error. 
2. A separate function, in order to troubleshoot a single docstring.

**Comment by mortenpi** [comment] 2022-07-07 07:38
For (1), you should be able to do it with `doctest(MyModule, manual = false)`. (2) would indeed be nice to have.

**Comment by odow** [comment] 2023-11-01 02:02
Closing a duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/1213

**Closed by odow** 2023-11-01 02:02 UTC
Labels: Type: Enhancement
