### ISSUE TITLE
Improve the link vs collapse UX in docstring headers

### ISSUE THREAD

**Issue by gdalle** [JuliaDocs/Documenter.jl#2476] opened 2024-03-07 10:42 UTC
Is there a way to avoid that? Or is it something we want, and if so why?

**Comment by gdalle** [comment] 2024-03-08 09:08
Found the trick: you gotta click on the frame but outside of the name itself (which is a link)

**Comment by fredrikekre** [comment] 2024-03-08 09:15
Perhaps it shouldn't behave like a link when the docstring is folded.

**Comment by mortenpi** [comment] 2024-03-10 07:47
Let me reopen this -- I thought we had an issue for this, but I can't find one. We would definitely want to improve how the link vs collapsing of the docstring works. The fact that clicking on the text part does both is not ideal.

**Comment by fredrikekre** [comment] 2024-03-13 18:59
Basically a duplicate of #2204

**Comment by mortenpi** [comment] 2024-03-13 23:18
It is. That was the issue I wasn't able to find before.

**Closed by mortenpi** 2024-03-13 23:18 UTC
Labels: Type: Bug, Format: HTML
