### ISSUE TITLE
Handle control characters in docstrings when building PDFs

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#1467] opened 2020-11-09 04:47 UTC
Currently, if you somehow manage to end up with e.g. a `\0` in a docstring, it will get literally written into the `.tex` file, which fails the `latexmk` compilation. Probably also true for other control characters. We should probably write them out as escape sequences in TeX.

X-ref: JuliaLang/julia#38356

**Comment by odow** [comment] 2023-11-01 01:33
Closing as a duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/2226

**Closed by odow** 2023-11-01 01:33 UTC
Labels: Type: Bug, Format: LaTeX
