### ISSUE TITLE
Only the first one has color highlighting in case of multiple methods

### ISSUE THREAD

**Issue by ShuhuaGao** [JuliaDocs/Documenter.jl#1547] opened 2021-03-11 05:35 UTC
See the following example.
```julia
"""
    dummy(x::Integer, y::AbstractVector{<:AbstractFloat}, z::String)::Bool

A dummy function to reproduce the issue.
"""
function dummy(x::Integer, y::AbstractVector{<:AbstractFloat}, z::String)::Bool end

"""
    dummy(x::Integer, y::AbstractVector{<:AbstractFloat})::Bool

A dummy function to reproduce the issue.
"""
function dummy(x::Integer, y::AbstractVector{<:AbstractFloat})::Bool end
```
In the generated HTML by ` ```@docs dummy ``` ` only the first `dummy` method is coloured properly.
![image](https://user-images.githubusercontent.com/20141984/110740615-517b9880-826e-11eb-9e62-0f374669cb2c.png)

The same issue can also be noticed in the screenshot present in #1523.

Version:
```
[e30172f5] Documenter v0.26.3
```

**Comment by fredrikekre** [comment] 2021-03-11 09:26
Looks like perhaps https://github.com/JuliaDocs/Documenter.jl/pull/980 didnt't cover this case? I thought it would do the highlighting on each docstring rather than the combined one (as happens now IIUC)?

**Comment by ShuhuaGao** [comment] 2021-03-11 10:04
No highlighting in my test. Could you reproduce the above issue?

**Comment by mortenpi** [comment] 2021-03-17 23:24
Yep, can confirm that this is an issue.

**Comment by odow** [comment] 2023-11-01 01:37
Closing as a duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/1101

**Closed by odow** 2023-11-01 01:37 UTC
Labels: Type: Bug, help wanted
