### ISSUE TITLE
extract lines from file for @example

### ISSUE THREAD

**Issue by andrewning** [JuliaDocs/Documenter.jl#1207] opened 2019-12-03 05:51 UTC
I really like using the `@example` feature.  However, I also like to maintain a separate example scrirpt that has the code without all the accompanying words.  I can do that now, but then I have two copies I need to keep in sync.  Let's say I have a script example.jl.  Is there a way I can specify lines to pull out from example.jl to insert into `@example` blocks?

**Comment by fredrikekre** [comment] 2019-12-03 06:15
I wrote https://github.com/fredrikekre/Literate.jl for just this purpose.

**Comment by andrewning** [comment] 2019-12-03 08:12
Awesome!  This looks great. I’ll try it out. Thanks.

**Comment by mortenpi** [comment] 2019-12-03 10:10
Literate is a good solution for this. But also grabbing at-example blocks from a file I would consider a duplicate of #499, so I'll close this.

**Closed by mortenpi** 2019-12-03 10:10 UTC
