### ISSUE TITLE
Add ability to copy code from snippets

### ISSUE THREAD

**Issue by odow** [JuliaDocs/Documenter.jl#1644] opened 2021-07-12 20:14 UTC
Github (recently? I only just noticed) introduced a thing to copy the code in a snippet. It would be cool if Documenter could do this too.

This SO looks helpful:
https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript

## Screenshots

![image](https://user-images.githubusercontent.com/8177701/125349504-bf1d0a00-e3b1-11eb-8e74-4d21d03bbbef.png)

![image](https://user-images.githubusercontent.com/8177701/125349524-c3e1be00-e3b1-11eb-94d2-b8006d3b3a2a.png)

**Comment by fredrikekre** [comment] 2021-07-12 20:16
Duplicate of #1055 (and there is WIP here: https://github.com/JuliaDocs/Documenter.jl/pull/1454)

**Closed by fredrikekre** 2021-07-12 20:16 UTC

**Comment by odow** [comment] 2021-07-12 20:22
Oops. I tried searching but obviously not hard enough.
