### ISSUE TITLE
Clicking on another docs version should point to the equivalent page

### ISSUE THREAD

**Issue by jtrakk** [JuliaDocs/Documenter.jl#1619] opened 2021-06-30 19:07 UTC
If I'm on the v1.5 Filesystem docs and I click on the v1.6 link in the bottom-left corner, it goes to the home page https://docs.julialang.org/en/v1.6/, not the Filesystem page, which is annoying. I want to go to the equivalent page of the other version.

@fredrikekre says

> For the Julia manual you should always be on the v1 version though, it is valid for all of Julia 1.X.

The v1 version differs from earlier versions in some ways, like including methods that don't exist in earlier versions and will confuse earlier readers. Also reading the _next_ (prerelease) version's docs may show what is coming soon.

**Comment by fredrikekre** [comment] 2021-06-30 19:08
> The v1 version differs from earlier versions in some ways, like including methods that don't exist in earlier versions and will confuse earlier readers.

Do you have any examples? Those should all have compat annotations.

**Comment by jtrakk** [comment] 2021-06-30 19:30
I see, not as confusing as I thought then. Still it would be nice to have.

**Comment by fredrikekre** [comment] 2021-06-30 19:33
Yea, I guess it can be on a "best-effort" since it can't be guaranteed that the same page exist on the other version.

**Comment by mortenpi** [comment] 2021-07-19 05:16
I think it should be possible to check in the browser if the URL in the other version 404-s or not, and decide based on that.

**Comment by odow** [comment] 2023-11-01 01:44
Closing as a duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/858

**Closed by odow** 2023-11-01 01:44 UTC
Labels: Type: Enhancement, Format: HTML
