### ISSUE TITLE
Travis CI build non responsive for 10m

### ISSUE THREAD

**Issue by Ward9250** [JuliaDocs/Documenter.jl#45] opened 2016-05-05 19:39 UTC
Hi,

On Bio.jl travis builds for julia v0.4 on OSX we've started to experience build failures even though all tests pass, the log indicating something freezes or becomes non-responsive after docs deployment. In the travis log it will say "Skipping docs deployment" for a merge into the master branch, and then will be non responsive for 10m. So I'm just investigating to see if this is Documenter.jl related.

This is the current log for Bio.jl master: https://travis-ci.org/BioJulia/Bio.jl/jobs/128102434

Many thanks,
Ben.

**Comment by MichaelHatherly** [comment] 2016-05-10 14:59
Sorry for not being very responsive here. I'll try take a look at this in the next few days.

Is this just happening on travis OSX? Or have you been able to reproduce locally too?

**Comment by bicycle1885** [comment] 2016-05-11 10:23
This is not reproducible on my OS X. So, I'm not sure whether this is due to a bug of Documenter.jl.

**Comment by MichaelHatherly** [comment] 2016-05-11 10:48
The OSX travis build for Documenter itself completes fine, so might have something to do with how long tests are taking for Bio.jl. Might be worth seeing what happens if doc gen is moved prior to other parts of the build such as code coverage.

There's also another possible OSX issue, https://github.com/MichaelHatherly/Documenter.jl/issues/44 (`bad file descriptor`), that *might* be related.

**Comment by Ward9250** [comment] 2016-05-11 11:46
I can confirm as @bicycle1885 says, my OSX does not do this either. I can try and swap the order and see what happens.

**Comment by Ward9250** [comment] 2016-05-11 12:29
Hi @MichaelHatherly,

I swapped the order of Documenter with Coveralls steps as you suggested (So the order was Tests -> Documenter -> Coveralls). The build only got as far as "Skipping Docs Deployment", and did not go on to the coveralls step. Compared to before (Tests -> Coveralls -> Documenter), which would complete the coveralls step, and the Documenter step, and then hang. The build is here: https://travis-ci.org/BioJulia/Bio.jl/jobs/129402418.  

Best,
@Ward9250

**Comment by MichaelHatherly** [comment] 2016-05-11 13:31
Thanks for checking. Seems like it is more than likely a Doucmenter issue then. I'll see if I can replicate it on travis myself.

**Comment by MichaelHatherly** [comment] 2016-05-12 20:52
Turning off doctesting with `makedocs(doctest = false)` allowed the build to finish, so this is most probably a problem with the output redirection code in Documenter. (Until I've resolved it you could conditionally disable doctests on the OSX 0.4 build to allow it to finish properly.)

**Comment by Ward9250** [comment] 2016-05-12 21:29
Thanks! I've added a conditional @osx? macro! :)

**Comment by MichaelHatherly** [comment] 2016-06-12 17:40
Closed by #93 hopefully. Let me know if that's not the case though.

**Closed by MichaelHatherly** 2016-06-12 17:40 UTC
Labels: Priority: High, Status: In Progress, Type: Bug
