### ISSUE TITLE
at-repl/example etc. not captured in note blocks

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaDocs/Documenter.jl#945] opened 2019-02-07 15:34 UTC
When I tried putting a `@repl` block inside a note, it doesn't get evaluated.

```
!!! note
    
    You can see a more detailed description of any formula or term with an
    `IOContext` where `:limit=>false`:
    
    ```@repl 1
    show(IOContext(stdout, :limit=>false), f)
    ```
```

The contents of the `@repl` block get passed through in a `pre` block, and not evaluated.

**Comment by fredrikekre** [comment] 2019-02-07 15:36
Duplicate of  #491

**Closed by fredrikekre** 2019-02-07 15:36 UTC
