### ISSUE TITLE
Sidebar navigation scrolls to top on clicking an entry

### ISSUE THREAD

**Issue by halirutan** [JuliaDocs/Documenter.jl#564] opened 2017-09-11 15:44 UTC
The official online documentation of Julia consists of a navigation menu on the left and the content on the right

![doc](http://i.imgur.com/5aW1NnS.png)

Whenever you click on one of the main entries that is farther down the navigation menu (e.g. "Essentials") the page loads in the content area, but then the navigation bar scrolls right back to the top.

This does not happen if you click an item that is on the level 2 of the navigation! Can this be fixed?

My system is Linux with a Chrome browser and the behaviour was verified by a second user.

**Comment by mortenpi** [comment] 2017-09-13 16:09
The gist of the issue is that the top level navigation item actually loads a new page (as opposed to jumping to in-page anchors). Would indeed be nice if it would center the current page in the navigation menu on page load.

On a slight tangent -- it could be nice to still show the version selector and search box even if you have scrolled down as well.

Both require some js magic I think. Up for grabs.

**Comment by mauro3** [comment] 2017-11-07 21:33
I'll add the word "sidebar" here as I did not find this issue when opening #594, as I searched for sidebar.

**Comment by halirutan** [comment] 2017-11-08 15:43
@mauro3 I changed the title.

**Comment by fredrikekre** [comment] 2019-01-24 10:12
fixed by #792

**Closed by fredrikekre** 2019-01-24 10:12 UTC
Labels: Type: Enhancement
