### ISSUE TITLE
Add URL in makedocs pages

### ISSUE THREAD

**Issue by tpoisot** [JuliaDocs/Documenter.jl#2572] opened 2024-09-12 13:49 UTC
I'm looking to do something where some entries in the sidebar would redirect to other sites (in my case, to the doc page of other packages).

Is this something that is feasible in the current state of the package? If not, would you be open to a PR?

**Comment by mortenpi** [comment] 2024-09-13 02:26
Duplicate of #344. A short answer is that yea, this is something worth supporting, so a PR would definitely be welcome. Not immediately clear how to make it work in the PDF/LaTeX output though.

**Closed by mortenpi** 2024-09-13 02:26 UTC
