### ISSUE TITLE
`$BASE_URL/MyPackage.jl/` does not automatically redirect to `$BASE_URL/MyPackage.jl/stable/`

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaDocs/Documenter.jl#1314] opened 2020-05-05 17:19 UTC
This might just be a misconfiguration on my end.

This works: https://juliahealth.org/HealthBase.jl/stable/

And this works: https://juliahealth.org/HealthBase.jl/dev/

But this does not work: https://juliahealth.org/HealthBase.jl/

I would have expected to https://juliahealth.org/HealthBase.jl/ to redirect to https://juliahealth.org/HealthBase.jl/stable/

For example, https://juliadocs.github.io/Documenter.jl/ redirects to https://juliadocs.github.io/Documenter.jl/stable/

Is there a way for Documenter.jl to automatically set up the redirect of `$BASE_URL/MyPackage.jl/` to `$BASE_URL/MyPackage.jl/stable/`?

**Comment by fredrikekre** [comment] 2020-05-05 17:42
Duplicate of #937

**Comment by fredrikekre** [comment] 2020-05-05 17:43
> Is there a way for Documenter.jl to automatically set up the redirect of $BASE_URL/MyPackage.jl/ to $BASE_URL/MyPackage.jl/stable/?

Not through Documenter, but it is a one-time setup to do it yourself, just add this file: https://github.com/JuliaDocs/Documenter.jl/blob/gh-pages/index.html

**Closed by fredrikekre** 2020-05-05 17:42 UTC
