### ISSUE TITLE
Improve documentation using packages in doctests for display

### ISSUE THREAD

**Issue by bkamins** [JuliaDocs/Documenter.jl#1564] opened 2021-04-10 07:15 UTC
Recently in DataFrames.jl we had the following issue with running doctests https://github.com/JuliaData/DataFrames.jl/issues/2705.

The problem was that the Documenter.jl documentation uses what was actually `used` in make.jl to format display not what is `used` in the doctests.

So e.g. the following code:
```
using CategoricalArrays
categorical(["a"])
```
produces the following array signature:
```
CategoricalArrays.CategoricalArray{String,1,UInt32}
```
instead of correct:
```
CategoricalArray{String,1,UInt32}
```
The issue is resolved by adding `using CategoricalArrays` also to make.jl.

I could not find any documentation that for producing display what is used in make.jl is respected (and not what you use in the actual doctest).

Maybe it is documented then sorry for raising this issue and it can be closed. However, I could not find this information.

**Comment by fredrikekre** [comment] 2021-04-12 11:36
This is just a quirk in Julia's display system where names are not displayed fully qualified if they are available in `Main`. Closing as a duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/944.

**Closed by fredrikekre** 2021-04-12 11:36 UTC
Labels: Type: Documentation, help wanted
