### ISSUE TITLE
Default font for REPL "output" produces poor alignment w/ box-drawing unicode

### ISSUE THREAD

**Issue by thchr** [JuliaDocs/Documenter.jl#1561] opened 2021-04-06 13:35 UTC
E.g., using the PrettyTables package leads to unaligned columns, as below (see also examples in [PrettyTables' documentation](https://ronisbr.github.io/PrettyTables.jl/stable/man/text_backend/#Cropping)):
![image](https://user-images.githubusercontent.com/26799210/113718331-871f7000-96ba-11eb-836d-76149c2f0418.png)
There's some issues with the font (is it Julia Mono?) not being truly monospace or with it falling back to another font perhaps.

In an ideal world, it would be possible to easily change the various fonts used in documentation (https://github.com/JuliaDocs/Documenter.jl/issues/973) - but having a genuinely monospace font for REPL display would be lovely in the meanwhile. 
(If this is just a fallback issue, then #973 may be sufficient for this issue)

**Comment by fredrikekre** [comment] 2021-04-06 15:01
Duplicate of #618.

**Closed by fredrikekre** 2021-04-06 15:01 UTC

**Comment by cormullion** [comment] 2021-04-15 10:00
> (is it Julia Mono?)

I hope not... :) If it were, it would look like this (macOS/Safari):

<img width="846" alt="Screenshot 2021-04-15 at 10 57 56" src="https://user-images.githubusercontent.com/52289/114851238-8765ec80-9dd9-11eb-9173-f756ffd5dbae.png">

**Comment by fredrikekre** [comment] 2021-04-15 10:09
I would be in favor of using JuliaMono as the default font for code. It looks like JuliaMono is now available from a proper CDN so I assume infrastructure wouldn't be a problem?

It would at least be nice to include some docs on how to change it (e.g. https://github.com/JuliaDiff/ChainRulesCore.jl/pull/293)

**Comment by cormullion** [comment] 2021-04-15 10:18
I've seen the (Google?) CDN for Lato/Roboto fail once (a Sunday morning a few years ago), so no system is going to be perfect...   Given how awesome all the Julia package infrastructure people are, perhaps serving a few 800 Kb font files wouldn't be too much of an extra load? 😄

**Comment by fredrikekre** [comment] 2021-04-15 10:28
I mean, it seems to be available from https://cdn.jsdelivr.net/gh/cormullion/juliamono/webfonts/JuliaMono-Regular.woff2 so that shouldn't hit any Julia-related infrastructure at all, right?

**Comment by cormullion** [comment] 2021-04-15 10:32
Yes, that's the current CDN. It's just that that service appears to be intended more for (or mainly for) JavaScript and Node (NPM) packages. Should they ever decide to not support certain types of file, perhaps that would then be a problem. But that's true of most  online services anyway, so ¯\\\_(ツ)_/¯...

**Comment by fredrikekre** [comment] 2021-04-15 10:35
I see. Would it be possible to use GH releases for individual files? I imagine GH has some type of CDN-like cache system too.

**Comment by fredrikekre** [comment] 2021-04-15 10:37
Actually, we can probably put it on something like `https://julialang.org/assets/...`. That website uses Fastly CDN I believe, so that should be fine.

**Comment by cormullion** [comment] 2021-04-16 07:58
Interesting idea - I'll open an issue and see what happens...
