### ISSUE TITLE
Allow at-blocks in container blocks

### ISSUE THREAD

**Issue by kalmarek** [JuliaDocs/Documenter.jl#719] opened 2018-05-08 06:39 UTC
I have an issue with `@docs` and lists:

indenting `@docs` block just by two spaces (to keep it aligned with bulletlist) does not find the docstring (there is just a code-block with `func` in the html output). 
However dedenting `@docs` block produces the correct output, but breaks the list indentation.

Is indentation not supported, or I'm doing something wrong?

**Comment by fredrikekre** [comment] 2018-05-08 06:55
Well, it is not supported ATM but I see no reason not to allow this. The reason it is not working is that
```julia
julia> A = Markdown.parse("""
       - Hello
         ```@docs
         foo
         ```
       """);

julia> B = Markdown.parse("""
       - Hello
       ```@docs
       TestPackage.foo
       ```
       """);

julia> A.content
1-element Array{Any,1}:
 Base.Markdown.List(Any[Any[Base.Markdown.Paragraph(Any["Hello"]), Base.Markdown.Code("@docs", "foo")]], -1)

julia> B.content
2-element Array{Any,1}:
 Base.Markdown.List(Any[Any[Base.Markdown.Paragraph(Any["Hello"])]], -1)
 Base.Markdown.Code("@docs", "TestPackage.foo")
```
where we only look at the "top level" content, and i `A` here the `@docs` block is inside the list instead of its own top level markdown object.

If we allow this we should probably also allow indented `@examples`, `jldoctest` etc.

**Comment by kalmarek** [comment] 2018-05-08 07:12
that would be great!

**Comment by fredrikekre** [comment] 2019-02-07 15:36
Duplicate of #491

**Closed by fredrikekre** 2019-02-07 15:36 UTC
Labels: Type: Decision, Type: Enhancement
