### ISSUE TITLE
How to make sidebar headings reference an internal page?

### ISSUE THREAD

**Issue by fsaad** [JuliaDocs/Documenter.jl#2039] opened 2023-02-13 19:42 UTC
Consider the **Manual** heading in the sidebar shown below; is it possible for this heading to be a link to an _internal_ page, such as `manual.md`? The related issue https://github.com/JuliaDocs/Documenter.jl/issues/344 is about external links.

<img src="https://user-images.githubusercontent.com/5721897/218555690-a4a79009-7feb-4339-b5fd-bd585fa10544.png"  width="30%">

**Comment by mortenpi** [comment] 2023-04-01 02:55
So, the short answer is no. There are two reasons for this:

1. We don't syntax for that in the `pages` argument (but something could probably be invented).
2. It is possible for those to be become collapsed, in which case the click actions on that item would conflict.

We could think about a specific proposal though.

**Comment by fsaad** [comment] 2023-04-05 06:53
> It is possible for those to be become collapsed, in which case the click actions on that item would conflict.

The Sphinx book theme handles this case by having the "text" and "arrow" be separate clickable items, see, e.g., https://sphinx-book-theme.readthedocs.io/en/stable/

![image](https://user-images.githubusercontent.com/5721897/230003557-01bfc65e-cd43-420d-97ff-50fb26e28ce3.png)

**Comment by odow** [comment] 2023-11-01 02:28
Closing as duplicate of #701

**Closed by odow** 2023-11-01 02:28 UTC
Labels: Type: Enhancement, Status: Speculative, Format: HTML
