### ISSUE TITLE
Add Filter option to at-index

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#1041] opened 2019-06-19 00:05 UTC
Similar to the `Filter` of at-autodocs. Would allow the user to pass a custom filtering function that determines which docstrings appear in the index.

**Comment by odow** [comment] 2023-11-01 02:02
Closing as a duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/1877

**Closed by odow** 2023-11-01 02:02 UTC
Labels: Type: Feature
