### ISSUE TITLE
 Markdown2 conversion error for a docstring in BPFnative.API.Network

### ISSUE THREAD

**Issue by lawless-m** [JuliaDocs/Documenter.jl#1775] opened 2022-03-10 10:42 UTC
I *think* the offending string is in [network.jl](https://github.com/lawless-m/BPFnative.jl/blob/master/src/network.jl)

make.jl works locally, this is only on Github

The code isn't really mine, I forked BPFnative.jl to add documentation so I could learn about it

https://github.com/lawless-m/BPFnative.jl

```
module Network
    using CBinding
    c`-std=c99 -fparse-all-comments`
    const c"__u8" = UInt8
    const c"__u16" = UInt16
    const c"__u32" = UInt32
    const c"__be8" = UInt8
    const c"__be16" = UInt16
    const c"__be32" = UInt32
    const c"__sum16" = UInt16
    c"#include <linux/if_ether.h>"j
    c"#include <linux/ip.h>"j
    c"#include <linux/in.h>"j
    c"#include <linux/tcp.h>"j
end
```

```
Run julia --project=docs/ docs/make.jl
  julia --project=docs/ docs/make.jl
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
    DOCUMENTER_KEY: 
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
┌ Error: Markdown2 conversion error for a docstring in BPFnative.API.Network.
│ This is a bug — please report this on the Documenter issue tracker
│   docstr.data =
│    Dict{Symbol, Any} with 5 entries:
│      :typesig    => Union{}
│      :module     => BPFnative.API.Network
│      :linenumber => 147
│      :binding    => BPFnative.API.Network.@c"MCAST_JOIN_GROUP"
│      :path       => "/home/runner/.julia/packages/CBinding/kBUap/src/context.…
└ @ Documenter.DocTests ~/.julia/packages/Documenter/tUp2d/src/DocTests.jl:80
ERROR: LoadError: MethodError: Cannot `convert` an object of type Documenter.Utilities.Markdown2.Link to an object of type Vector{Documenter.Utilities.Markdown2.MarkdownInlineNode}
Closest candidates are:
  convert(::Type{T}, !Matched::LinearAlgebra.Factorization) where T<:AbstractArray at /opt/hostedtoolcache/julia/1.7.2/x64/share/julia/stdlib/v1.7/LinearAlgebra/src/factorization.jl:58
  convert(::Type{T}, !Matched::AbstractArray) where T<:Array at /opt/hostedtoolcache/julia/1.7.2/x64/share/julia/base/array.jl:554
  convert(::Type{T}, !Matched::T) where T<:AbstractArray at /opt/hostedtoolcache/julia/1.7.2/x64/share/julia/base/abstractarray.jl:16
  ...
Stacktrace:
  [1] Documenter.Utilities.Markdown2.Paragraph(nodes::Documenter.Utilities.Markdown2.Link)
    @ Documenter.Utilities.Markdown2 ~/.julia/packages/Documenter/tUp2d/src/Utilities/Markdown2.jl:120
  [2] _convert_block(b::Markdown.Paragraph)
    @ Documenter.Utilities.Markdown2 ~/.julia/packages/Documenter/tUp2d/src/Utilities/Markdown2.jl:227
  [3] iterate
    @ ./generator.jl:47 [inlined]
  [4] collect_to!(dest::Vector{Documenter.Utilities.Markdown2.CodeBlock}, itr::Base.Generator{Vector{Any}, typeof(Documenter.Utilities.Markdown2._convert_block)}, offs::Int64, st::Int64)
    @ Base ./array.jl:782
  [5] collect_to_with_first!(dest::Vector{Documenter.Utilities.Markdown2.CodeBlock}, v1::Documenter.Utilities.Markdown2.CodeBlock, itr::Base.Generator{Vector{Any}, typeof(Documenter.Utilities.Markdown2._convert_block)}, st::Int64)
    @ Base ./array.jl:760
  [6] _collect(c::Vector{Any}, itr::Base.Generator{Vector{Any}, typeof(Documenter.Utilities.Markdown2._convert_block)}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base ./array.jl:754
  [7] collect_similar
    @ ./array.jl:653 [inlined]
  [8] map
    @ ./abstractarray.jl:2849 [inlined]
  [9] convert(#unused#::Type{Documenter.Utilities.Markdown2.MD}, md::Markdown.MD)
    @ Documenter.Utilities.Markdown2 ~/.julia/packages/Documenter/tUp2d/src/Utilities/Markdown2.jl:214
 [10] doctest(docstr::Base.Docs.DocStr, mod::Module, doc::Documenter.Documents.Document)
    @ Documenter.DocTests ~/.julia/packages/Documenter/tUp2d/src/DocTests.jl:78
 [11] doctest(blueprint::Documenter.Documents.DocumentBlueprint, doc::Documenter.Documents.Document)
    @ Documenter.DocTests ~/.julia/packages/Documenter/tUp2d/src/DocTests.jl:57
 [12] runner(#unused#::Type{Documenter.Builder.Doctest}, doc::Documenter.Documents.Document)
    @ Documenter.Builder ~/.julia/packages/Documenter/tUp2d/src/Builder.jl:213
 [13] dispatch(#unused#::Type{Documenter.Builder.DocumentPipeline}, x::Documenter.Documents.Document)
    @ Documenter.Utilities.Selectors ~/.julia/packages/Documenter/tUp2d/src/Utilities/Selectors.jl:170
 [14] #2
    @ ~/.julia/packages/Documenter/tUp2d/src/Documenter.jl:266 [inlined]
 [15] cd(f::Documenter.var"#2#3"{Documenter.Documents.Document}, dir::String)
    @ Base.Filesystem ./file.jl:110
 [16] #makedocs#1
    @ ~/.julia/packages/Documenter/tUp2d/src/Documenter.jl:265 [inlined]
 [17] top-level scope
    @ ~/work/BPFnative.jl/BPFnative.jl/docs/make.jl:6
in expression starting at /home/runner/work/BPFnative.jl/BPFnative.jl/docs/make.jl:6
Error: Process completed with exit code 1.

```

**Comment by mortenpi** [comment] 2022-03-26 07:29
This is a duplicate of #1708.

**Closed by mortenpi** 2022-03-26 07:29 UTC
