### ISSUE TITLE
Files not found have no warnings

### ISSUE THREAD

**Issue by untoreh** [JuliaDocs/Documenter.jl#2359] opened 2023-11-28 13:29 UTC
If I have a block like
````
```@autodocs
Modules = [MyModule]
Pages = ["api1.jl", "api2.jl"]
```
````
And `api2.jl` does not exist, nothing will be rendered. There is no warning thrown when a a file in the pages list does not exist.

**Comment by fredrikekre** [comment] 2023-11-28 13:40
You have to submit a reproducible example, this is what I get
```
ERROR: LoadError: 'api2.jl' is not an existing page!
```

**Comment by goerz** [comment] 2023-11-28 14:06
Duplicate of #2302

**Closed by goerz** 2023-11-28 14:06 UTC
