### ISSUE TITLE
missing methods with common documentation

### ISSUE THREAD

**Issue by adamglos92** [JuliaDocs/Documenter.jl#705] opened 2018-04-13 08:01 UTC
Right know I am developing a Module, in which several functions have the same name and documentation, like
```
"""
# doc
"""
function f(a::Int)
   ...
end,

function f(a::Float64)
   ...
end,

function f(a::Complex128)
   ...
end
```
Right know I include only reference to `f(a::Int)`, but the Documenter.jl says none of the functions is documented. How to suppress such warning?

**Comment by mortenpi** [comment] 2018-04-15 21:36
I don't think this is related to the `where` syntax. In this case, it seems that the commas after the `end`s might be causing trouble. Does it work the way you want if you remove the commas?

**Comment by adamglos92** [comment] 2019-02-01 20:49
The problem is with may package QuantumWalk https://github.com/QuantumWalks/QuantumWalk.jl.

**Comment by knuesel** [comment] 2021-01-25 13:28
@adamglos92 I had a look at your pacage but it seems the problem is fixed? Can you still reproduce it or can this issue be closed?

**Comment by adamglos92** [comment] 2021-01-25 15:29
Not sure:) I decided to be more sparse with my comments, so this is not relevant for me now

**Comment by mortenpi** [comment] 2021-02-09 22:53
Let's close this then. Feel free to open another issue if something like this crops up again.

**Closed by mortenpi** 2021-02-09 22:53 UTC
Labels: Type: Question
