### ISSUE TITLE
HTML footnotes end up in text instead of at the end

### ISSUE THREAD

**Issue by tpapp** [JuliaDocs/Documenter.jl#1104] opened 2019-08-20 12:06 UTC
In this generated documentation:

https://tamaspapp.eu/DynamicHMC.jl/latest/

Generated from sources like:

https://github.com/tpapp/DynamicHMC.jl/blob/master/docs/src/index.md

With a makedocs script at

https://github.com/tpapp/DynamicHMC.jl/blob/master/docs/make.jl

using Documenter 0.23, the footnotes end up where written, instead of at the end of the HTML page.

**Comment by tpapp** [comment] 2019-08-20 14:49
Same with Documenter 0.22.6.

**Comment by tpapp** [comment] 2019-08-20 14:54
But current `master`, ie
```julia
  [e30172f5] Documenter v0.23.2 #master (https://github.com/JuliaDocs/Documenter.jl.git)
```
works fine.

**Comment by mortenpi** [comment] 2019-08-20 19:13
Yeah, I changed this in #1043. So nothing else to really do here?

**Comment by tpapp** [comment] 2019-08-20 19:21
It would be great to have a release with that fix if that's feasible.

**Comment by mortenpi** [comment] 2019-08-20 19:30
This will be in 0.24.0. The change is not really easily backportable (and is not a bugfix). I hope to tag it next week, but I can't quite promise it -- it's a pretty big release. But I will definitely try to have the release out within the next few weeks.

I'll close this issue as the change has already been implemented on master.

**Closed by mortenpi** 2019-08-20 19:30 UTC
Labels: Format: HTML, Type: Enhancement

**Comment by mortenpi** [comment] 2019-08-20 19:31
For DynamicHMC though -- you can always have a `docs/Manifest.toml` and pin Documenter to `master` there.
