### ISSUE TITLE
Allow for setting a webpage title independently of the title shown in the sidebar

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDocs/Documenter.jl#1371] opened 2020-07-19 15:15 UTC
The sidebar is quite small, so it would be nice to allow a different title to the actual header since that's what shows up in search engines

**Comment by mortenpi** [comment] 2020-07-19 23:06
You mean what goes into the `<title>` element, right? Possibly something that could be done with an at-meta block option.

**Comment by ChrisRackauckas** [comment] 2020-07-20 00:24
yeah exactly

**Comment by odow** [comment] 2023-11-01 02:06
Closing as a duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/1898

**Closed by odow** 2023-11-01 02:06 UTC
Labels: Type: Enhancement, help wanted, Format: HTML
