### ISSUE TITLE
Newline needed for minted code block in pdf export

### ISSUE THREAD

**Issue by JRikken** [JuliaDocs/Documenter.jl#1160] opened 2019-10-14 14:47 UTC
When exporting to LaTeX (`makedocs()` with `format = LaTeX()`), the code listings at the start of the docstrings failed to print (only generating the vertical line in front of the code block). 

Adding a newline before the `\end{minted}` command in the generated tex file seems to solve this.
I've tried adding a newline to the corresponding `_println(io, "\\end{minted}\n")` call in `LaTeXWriter.jl`, this seems to do the trick as well. 

Docstring: 

```Julia
"""
    myFunction!(A, B, C)

My description
"""
```

I am using Julia 1.2.0 and MiKTex 2.9 on Windows 10

**Comment by mortenpi** [comment] 2022-03-25 02:05
It looks like it's not reproducible, so let's close it. We can always reopen it.

**Closed by mortenpi** 2022-03-25 02:05 UTC
Labels: Format: LaTeX
