### ISSUE TITLE
Deployment failure

### ISSUE THREAD

**Issue by andreasvarga** [JuliaDocs/Documenter.jl#2581] opened 2024-09-21 10:18 UTC
This is a recurring problem for me, which I encouter almost every time I start developing a new package. This time my strugle is with [PeriodicMatrices](https://github.com/andreasvarga/PeriodicMatrices).  

Although, I think I performed all settings according to Documenter's requirements (i.e., creating authentication SSH Deploy Keys, preparing a workflow configuration file called .github/workflows/documentation.yml with identical contents as in documentation, adding the public SSH key to my settings page for the GitHub repository, entering the name **documenter** as the title, and copying the public key into the Key field, allowing write access to Documenter to commit the generated documentation to the repo). 
The last failure can be seen [here](https://github.com/andreasvarga/PeriodicMatrices/actions/runs/10971717119/job/30467174625). 

I have no idea what to do. Any hint could be helpful for me. Thanks in advance.

**Comment by goerz** [comment] 2024-09-21 11:17
The relevant error still seems to be

```
┌ Error: Git failed to fetch git@github.com:andreasvarga/PeriodicMatrices.jl.git
│ This can be caused by a DOCUMENTER_KEY variable that is not correctly set up.
│ Make sure that the environment variable is properly set up as a Base64-encoded string
│ of the SSH private key. You may need to re-generate the keys with DocumenterTools.
└ @ Documenter ~/.julia/packages/Documenter/C1XEF/src/deploydocs.jl:380
```

So, some kind of misconfiguration of deploy keys, would be my guess.

> entering the name **documenter** as the title

I can't access your repo secrets, but I don't think there's anything that should be named `documenter` anywhere.

Things should work if you follow the instructions at https://documenter.juliadocs.org/stable/man/hosting/. Note that anything in there about "Travis CI" basically also applies to GitHub Actions. Travis used to be the go-to CI for open source until it collapsed and was replaced by GitHub Actions, but the Documenter documentation hasn't been fully updated.

You might also find https://www.youtube.com/watch?v=bEAb7nDxuDE useful, which is pretty up-to-date

I'm going to close the issue, since it's not really something that's actionable on the Documenter side (besides "improve the documentation", which is already on our radar), but feel free to add more comments if you need more help. In general, [Discourse](https://discourse.julialang.org) is probably a better place to get help with these kinds of issues.

**Closed by goerz** 2024-09-21 11:17 UTC

**Comment by andreasvarga** [comment] 2024-09-21 14:38
> So, some kind of misconfiguration of deploy keys, would be my guess.
> 
>     entering the name documenter as the title
> 
> I can't access your repo secrets, but I don't think there's anything that should be named documenter anywhere.

I mentioned this, being a request formulated in  the documentation (section [Authentication: SSH Deploy Keys](https://yichengdwu.github.io/Documenter.jl/stable/man/hosting/#travis-ssh)):

"Follow the instructions that are printed out, namely:

    1. Add the public ssh key to your settings page for the GitHub repository that you are setting up by following the .../settings/keys link provided. Click on Add deploy key, enter the name **documenter** as the title, and copy the public key into the **Key** field. Check **Allow write access** to allow Documenter to commit the generated documentation to the repo.

    2. Next add the long private key to the Travis settings page using the provided link. Again note that you should include no whitespace when copying the key. In the Environment Variables section add a key with the name DOCUMENTER_KEY and the value that was printed out. Do not set the variable to be displayed in the build log. Then click Add. "

I am using the same settings for other 5 packages and everything works as expected. So, I wonder if is a way to debug such failures ? As you understand, for me this could not be a closed issue!

**Comment by goerz** [comment] 2024-09-21 17:18
> I mentioned this, being a request formulated in the documentation

I don't get it. There's nothing there that would relate to "entering the name `documenter` as the title". I was just wondering if the issue is that where the documentation says to create "a key with the name `DOCUMENTER_KEY`", you might have used the name `documenter`, which then wouldn't work.

> I am using the same settings for other 5 packages and everything works as expected.

There's got to be *something* that's different between those 5 packages and this one. That would definitely be something to focus on for debugging.


> As you understand, for me this could not be a closed issue!

You absolutely have my sympathy for your difficulties with getting the documentation deployed. But the cause is in `PeriodicMatrices`, not in `Documenter`. So this issue tracker just isn't the right place.

> Would it be possible that CompatHelper inferes with the deployment process? 

No, I don't think so. I don't see how `CompatHelper` could possibly have any effect on deploying the documentation. But both issues may have the same underlying cause, which I think I just figured out: Your repository has the wrong name. You're missing the ".jl". The project has to have the name `PeriodicMatrices.jl`, not just `PeriodicMatrices`.  If you locally run `git clone git@github.com:andreasvarga/PeriodicMatrices.jl.git` (as the CI tries to do), you'll see the same issue. Running `git clone git@github.com:andreasvarga/PeriodicMatrices.git` works, but of course, the GitHub project name for Julia project *must* include the `.jl` (at least that's a requirement for registration in General).

This isn't to say you might not be having other issues with deploy keys as well, but you'll definitely have to rename your repo for things to work.

**Comment by goerz** [comment] 2024-09-21 17:22
> I am using the same settings for other 5 packages

The missing `.jl` suffix is definitely the difference compared to your other existing packages!

![CleanShot 2024-09-21 at 13 20 42@2x](https://github.com/user-attachments/assets/00b2ce9b-6750-4094-b94a-37526c118f8f)

**Comment by andreasvarga** [comment] 2024-09-21 18:10
This is a silly overlook of my part. I appologize for this. 

And, many thanks for your time, patience and sharp observation. 

And, it works now!
